apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.ordersclusterip1.name }}
  labels:
   app: {{ .Values.labelsapp }}
   role: clusterIP
  annotations:
   description: "This clusterIP connects the pod orders to the network"
spec:
  selector:
    name: {{ .Values.ordersclusterip1.podselector }}
  type: ClusterIP
  ports:
  - name: {{ .Values.ordersclusterip1.portname }}
    protocol: {{ .Values.ordersclusterip1.protocol }}
    port: {{ .Values.ordersclusterip1.port }}
    targetPort: {{ .Values.ordersclusterip1.targetport }}


